sudo: required
dist: trusty

language: java
cache:
  directories:
  - $HOME/.gradle
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xmx2500M"
script: ./gradlew build
deploy:
  - provider: script
    script: "./gradlew clean uploadArchives"
    skip_cleanup: true
    on:
      repo: OpenCubicChunks/CubicChunks
      all_branches: true
notifications:
  email: false
 
